name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5      

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        working-directory: POCOGenerator
        run: nuget restore POCOGenerator.sln

      - name: Build Solution
        working-directory: POCOGenerator
        run: |
          msbuild.exe POCOGenerator.sln /p:platform="Any CPU" /p:configuration="Release"
          
      - name: Create Archive Release
        uses: TheDoctor0/zip-release@master
        with:          
          filename: POCOGenerator.zip    
          path: bin\Release\          
          directory: POCOGenerator
          type: zip
          
      - name: Upload Archived Release      
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          directory: POCOGenerator
          upload_url: POCOGenerator
          asset_path: ./POCOGenerator.zip
          asset_name: POCOGenerator.zip
          asset_content_type: application/zip
